package com.challenge.Bank.controller;

import com.challenge.Bank.DTO.request.ClientRequestDTO;
import com.challenge.Bank.DTO.response.ClientResponseDTO;
import com.challenge.Bank.service.ClientService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/client")
public class ClientController {

    private final ClientService clientService;
    public ClientController(ClientService clientService) {
        this.clientService = clientService;
    }

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "busca todos os clientes",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public List<ClientResponseDTO> findAll() {
        return clientService.findAll();
    }

    @GetMapping(value = "/{id}",  produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "busca um cliente pelo id",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ClientResponseDTO findById(@PathVariable Long id) {
        return clientService.findById(id);
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "salva um novo usuário",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ClientResponseDTO save(@RequestBody ClientRequestDTO clientRequestDTO) {
        return clientService.save(clientRequestDTO);
    }

    @DeleteMapping(value = "/{id}")
    @Operation(
            summary = "desativa o usuário",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ResponseEntity<Void> deactivateUser(@PathVariable Long id) {
        clientService.deactivateUser(id);
        return ResponseEntity.ok().build();
    }

}
