package com.challenge.Bank.controller;

import com.challenge.Bank.DTO.request.TransactionRequestDTO;
import com.challenge.Bank.DTO.response.TransactionResponseDTO;
import com.challenge.Bank.service.TransactionService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("api/transacao/v1")
public class TransactionController {

    private final TransactionService transactionService;

    public TransactionController(TransactionService transactionService) {
        this.transactionService = transactionService;
    }

    @PostMapping(
            consumes = MediaType.APPLICATION_JSON_VALUE,
            produces = MediaType.APPLICATION_JSON_VALUE
    )
    @Operation(
            summary = "save transaction",
            description = "This endpoint is capable of saving a new transaction by providing only the transaction amount",
            tags = {"Transaction"},
            responses = {
                    @ApiResponse(description = "Created", responseCode = "201", content = @Content),
                    @ApiResponse(description = "Unprocessable Entity", responseCode = "422", content = @Content),
                    @ApiResponse(description = "Bad Request", responseCode = "400", content = @Content)
            }
    )
    public ResponseEntity<TransactionResponseDTO> save(@RequestBody TransactionRequestDTO transactionRequestDTO) {
        var saved = transactionService.save(transactionRequestDTO);

        return ResponseEntity.status(HttpStatus.CREATED).body(saved);
    }

    @DeleteMapping(value = "/{id}")
    @Operation(
            summary = "Deleting Transactions",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        transactionService.delete(id);
        return ResponseEntity.ok().build();
    }

}
