package com.challenge.Bank.card.controller.doc;

import com.challenge.Bank.card.DTO.CardResponseDTO;
import com.challenge.Bank.exceptions.ExceptionResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.ResponseEntity;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;


import java.util.UUID;

@Tag(name = "Card", description = "Registration and management of cards")
public interface CardControllerDoc {

    @Operation(
            summary = "Create a virtual card for an account",
            description = "Generates a new virtual card automatically and links it to an existing bank account. " +
                    "The card number, CVV, expiration date and holder name are all generated by the system based on " +
                    "the account owner's data. Each account can have only one card."
    )
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Card created successfully",
                    content = @Content(schema = @Schema(implementation = CardResponseDTO.class))),
            @ApiResponse(responseCode = "403", description = "Access denied",
                    content = @Content(schema = @Schema(implementation = ExceptionResponse.class))),
            @ApiResponse(responseCode = "404", description = "Account not found",
                    content = @Content(schema = @Schema(implementation = ExceptionResponse.class))),
            @ApiResponse(responseCode = "422", description = "Account already has a card",
                    content = @Content(schema = @Schema(implementation = ExceptionResponse.class)))
    })
    ResponseEntity<CardResponseDTO> create(
            @Parameter(description = "Unique identifier of the account that will own the card", example = "123e4567-e89b-12d3-a456-426614174000")
            UUID accountId
    );

}
