package com.challenge.Bank.clients.controller;

import com.challenge.Bank.clients.DTO.ClientRequestDTO;
import com.challenge.Bank.clients.DTO.ClientResponseDTO;
import com.challenge.Bank.clients.service.ClientService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/v1/client")
public class ClientController {

    private final ClientService clientService;
    public ClientController(ClientService clientService) {
        this.clientService = clientService;
    }

    @GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "busca todos os clientes",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ResponseEntity<List<ClientResponseDTO>> findAll() {
        return ResponseEntity.ok(clientService.findAll());
    }

    @GetMapping(value = "/{uuid}",  produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "busca um cliente pelo id",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ResponseEntity<ClientResponseDTO> findById(@PathVariable UUID uuid) {
        return ResponseEntity.ok(clientService.findById(uuid));
    }

    @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
    @Operation(
            summary = "salva um novo usuário",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ClientResponseDTO save(@RequestBody ClientRequestDTO clientRequestDTO) {
        return clientService.save(clientRequestDTO);
    }

    @DeleteMapping(value = "/{uuid}")
    @Operation(
            summary = "desativa o usuário",
            description = "This endpoint is capable of deleting transactions made based on the ID generated by the transaction",
            tags = {"Transactions"},
            responses = {
                    @ApiResponse(description = "ok", responseCode = "200", content = @Content),
            }
    )
    public ResponseEntity<Void> deactivateUser(@PathVariable UUID uuid) {
        clientService.deactivateUser(uuid);
        return ResponseEntity.ok().build();
    }

}
